name: Login E2E Test

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: self-hosted

    env:
      TEST_USER_EMAIL: test@ex.com
      TEST_USER_PASSWORD: pw1234

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Start server
        run: |
          cd server
          nohup node server.js > server.log 2>&1 &
          sleep 3

      - name: Install test deps
        run: |
          cd e2e
          npm install
          npx playwright install #--with-deps

      - name: Run Playwright tests
        run: |
          cd e2e
          npx playwright test
          
      - name: Upload Playwright Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            e2e/playwright-report
            e2e/test-results
            